In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Массив", arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив:\n", arr2)

zeros = np.zeros((3, 4))
print("Массив из нулей:\n", zeros)

ones = np.ones((2, 3))
print("Массив из единиц:\n", ones)

linspace = np.linspace(0, 10, 5)
print("Равномерно распределенные значения:", linspace)

random_arr = np.random.random((2, 3))
print("Массив со случайными значениями:\n", random_arr)

Массив [1 2 3 4 5]
Двумерный массив:
 [[1 2 3]
 [4 5 6]]
Массив из нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив из единиц:
 [[1. 1. 1.]
 [1. 1. 1.]]
Равномерно распределенные значения: [ 0.   2.5  5.   7.5 10. ]
Массив со случайными значениями:
 [[0.53162754 0.65570301 0.28901802]
 [0.09581613 0.66366511 0.82178716]]


In [4]:
print("Форма массива arr1:", arr1.shape)
print("Форма массива arr2:", arr2.shape)

print("Тип данных arr1:", arr1.dtype)
print("Тип данных arr2:", arr2.dtype)

int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("Целочисленный массив:", int_arr, "Тип:", int_arr.dtype)
print("Вещественный массив:", float_arr, "Тип:", float_arr.dtype)

Форма массива arr1: (5,)
Форма массива arr2: (2, 3)
Тип данных arr1: int64
Тип данных arr2: int64
Целочисленный массив: [1 2 3] Тип: int32
Вещественный массив: [1. 2. 3.] Тип: float64


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print("Исходный массив:", arr)

print("Первый элемент:", arr[0])
print("Последний элемент:", arr[-1])

print("Элементы с 1 по 3:", arr[1:4])
print("Первые три элемента:", arr[:3])
print("Все элементы, кроме первых двух:", arr[2:])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерный массив:\n", arr_2d)

print("Элемент во второй строке, третьем столбце:", arr_2d[1, 2])

print("Первая строка:", arr_2d[0, :])
print("Первый столбец:", arr_2d[:, 0])
print("Подматрица:\n", arr_2d[0:2, 1:3])

Исходный массив: [10 20 30 40 50]
Первый элемент: 10
Последний элемент: 50
Элементы с 1 по 3: [20 30 40]
Первые три элемента: [10 20 30]
Все элементы, кроме первых двух: [30 40 50]

Двумерный массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент во второй строке, третьем столбце: 6
Первая строка: [1 2 3]
Первый столбец: [1 4 7]
Подматрица:
 [[2 3]
 [5 6]]


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Массив a:", a)
print("Массив b:", b)

print("Сложение:", a + b)
print("Вычитание:", a - b)
print("Умножение:", a * b)
print("Деление:", a / b)
print("Возведение в степень:", a ** 2)

print("Умножение на число:", a * 3)
print("Сложение с числом:", a + 10)

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print("\nМатрица A:\n", matrix_a)
print("Матрица B:\n", matrix_b)
print("Матричное умножение:\n", np.dot(matrix_a, matrix_b))

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
Сложение: [ 6  8 10 12]
Вычитание: [-4 -4 -4 -4]
Умножение: [ 5 12 21 32]
Деление: [0.2        0.33333333 0.42857143 0.5       ]
Возведение в степень: [ 1  4  9 16]
Умножение на число: [ 3  6  9 12]
Сложение с числом: [11 12 13 14]

Матрица A:
 [[1 2]
 [3 4]]
Матрица B:
 [[5 6]
 [7 8]]
Матричное умножение:
 [[19 22]
 [43 50]]


In [7]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Исходные данные:", data)

print("Сумма:", np.sum(data))
print("Среднее значение:", np.mean(data))
print("Медиана:", np.median(data))
print("Стандартное отклонение:", np.std(data))
print("Дисперсия:", np.var(data))
print("Минимальное значение:", np.min(data))
print("Максимальное значение:", np.max(data))

data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерный массив:\n", data_2d)
print("Сумма всех элементов:", np.sum(data_2d))
print("Сумма по столбцам:", np.sum(data_2d, axis=0))
print("Сумма по строкам:", np.sum(data_2d, axis=1))
print("Среднее по столбцам:", np.mean(data_2d, axis=0))
print("Среднее по строкам:", np.mean(data_2d, axis=1))

Исходные данные: [ 1  2  3  4  5  6  7  8  9 10]
Сумма: 55
Среднее значение: 5.5
Медиана: 5.5
Стандартное отклонение: 2.8722813232690143
Дисперсия: 8.25
Минимальное значение: 1
Максимальное значение: 10

Двумерный массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Сумма всех элементов: 45
Сумма по столбцам: [12 15 18]
Сумма по строкам: [ 6 15 24]
Среднее по столбцам: [4. 5. 6.]
Среднее по строкам: [2. 5. 8.]
